import type { Metadata } from "next";
import "./globals.css";
import { Urbanist, Open_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import QueryProvider from "@/providers/query-provider";
import { Toaster } from "sonner";
import Sidebar from "@/components/layout/sidebar/sidebar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const urbanist = Urbanist({ subsets: ["latin"] });
const open_sans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open_sans",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-white", open_sans.variable, urbanist.className)}>
        <QueryProvider>
          <Toaster position="top-right" richColors />
          <Header />
          <div className="flex flex-col md:flex-row px-5 gap-4">
            {" "}
            <div className="md:basis-1/6 w-full">
              <Sidebar />
            </div>
            <div className="md:basis-5/6 w-full">
              <main className="min-h-screen">
                <div className="px-4">
                  <div className="flex flex-wrap gap-4">
                    <section className="w-full">{children}</section>
                  </div>
                </div>
              </main>
            </div>
          </div>

          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
