import type { Metadata } from "next";
import "./globals.css";
import { Urbanist, Open_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import QueryProvider from "@/providers/query-provider";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const urbanist = Urbanist({ subsets: ["latin"] });
const open_sans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open_sans",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("bg-background", open_sans.variable, urbanist.className)}
      >
        <QueryProvider>
          <Toaster position="top-right" richColors />
          <Header />
          <main className="min-h-screen">
            <div className="container mx-auto px-4">
              <div className="flex flex-wrap gap-4">
                {/* Nếu muốn áp dụng class như bạn nói, có thể truyền qua props hoặc dùng ở children */}
                <section className="w-full">{children}</section>
              </div>
            </div>
          </main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
